#!/usr/bin/env python3
"""Derive the ell range over which criterion 5's tolerance is meaningful.

    python scripts/derive_ell_range.py

Writes `diagnostics/ell-range-v1.0.0.txt`. The number in the release notes is
generated here, never asserted.

**Why there is a range at all.** Annals II's §8 comparison is a Sachs-Wolfe-only
result. (196) descends from (181), in which the acoustic modulation cos(k r_s) is
dropped by taking r_s* -> 0, and §8.3.2 sets the transfer function to unity. So
the comparison's accuracy is bounded by the term that was dropped, 1 - cos(k r_s),
with ell ~ k dEta_*.

Model: Annals II §8.3.2's own, n=1, h=0.5, Omega_B=0.05, flat matter-dominated
(Einstein-de Sitter), a_0 = 1, z_* = 1100.

**This also exercises finding B-3.** Eq. (199) as printed is correct only where
Gamma(m/2+1) = 1, that is at m = 0 and m = 2. The corrected identity carries
[(m/2)!]^2 in the denominator. (201) uses m = 2 and is right; (204) uses m = 1 and
is high by 2/sqrt(pi).
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from scipy.integrate import quad
from scipy.special import gamma, spherical_jn

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "diagnostics" / "ell-range-v1.0.0.txt"

# --- Annals II §8.3.2 model -------------------------------------------------
H, OMEGA_B, Z_STAR = 0.5, 0.05, 1100.0
OMEGA_GAMMA_H2 = 2.47e-5  # photon density parameter today
TOLERANCES = (0.01, 0.02, 0.05, 0.10)
ADOPTED_TOLERANCE = 0.05


def bessel_integral_numeric(m: int, ell: int) -> float:
    """int_0^inf dz z^{-m} j_ell(z)^2, by quadrature with an analytic tail."""
    f = lambda z: spherical_jn(ell, z) ** 2 / z**m  # noqa: E731
    total, a = 0.0, 1e-8
    for b in (1, 10, 50, 200, 1000, 5000, 20000):
        value, _ = quad(f, a, b, limit=400)
        total += value
        a = b
    return total + 1 / (2 * (1 + m) * a ** (1 + m))  # <sin^2> = 1/2


def bessel_integral_printed(m: float, ell: float) -> float:
    """Annals II (199) exactly as printed, p. 372."""
    return (
        (np.pi / 2 ** (m + 2))
        * gamma(m + 1)
        * gamma(ell - m / 2 + 0.5)
        / (gamma(m / 2 + 1) * gamma(ell + m / 2 + 1.5))
    )


def bessel_integral_corrected(m: float, ell: float) -> float:
    """(199) with [(m/2)!]^2 in the denominator. Finding B-3."""
    return (
        (np.pi / 2 ** (m + 2))
        * gamma(m + 1)
        * gamma(ell - m / 2 + 0.5)
        / (gamma(m / 2 + 1) ** 2 * gamma(ell + m / 2 + 1.5))
    )


def acoustic_scale() -> dict[str, float]:
    a_star = 1.0 / (1.0 + Z_STAR)
    r_baryon = 0.75 * (OMEGA_B * H**2 / OMEGA_GAMMA_H2) * a_star
    c_s = 1.0 / np.sqrt(3.0 * (1.0 + r_baryon))
    eta_0 = 2.0  # units of 1/H0, Einstein-de Sitter
    eta_star = eta_0 * np.sqrt(a_star)
    d_eta = eta_0 - eta_star
    r_s = c_s * eta_star  # the paper's own r_s ~ c_s eta approximation
    return {
        "R_star": r_baryon,
        "c_s": c_s,
        "eta_star": eta_star,
        "d_eta": d_eta,
        "r_s": r_s,
        "ell_A": np.pi * d_eta / r_s,
    }


def main() -> int:
    lines: list[str] = []
    w = lines.append

    w("Criterion 5 — the ell range over which the tolerance is meaningful")
    w("Generated by scripts/derive_ell_range.py. Do not edit by hand.")
    w("")
    w("B-3 — Annals II (199), p. 372, checked against the integral")
    w("  m   ell      numeric      printed/num   corrected/num")
    worst_printed = 0.0
    for m in (0, 1, 2, 3):
        for ell in (2, 10, 30):
            num = bessel_integral_numeric(m, ell)
            rp, rc = bessel_integral_printed(m, ell) / num, bessel_integral_corrected(m, ell) / num
            worst_printed = max(worst_printed, abs(rp - 1.0))
            w(f"  {m:1d}  {ell:4d}   {num:.8e}    {rp:.6f}      {rc:.6f}")
    w("")
    w(f"  printed form departs by up to {100 * worst_printed:.1f}% — exact only at m = 0, 2")
    w(f"  at m = 1, used by (204): high by 2/sqrt(pi) = {2 / np.sqrt(np.pi):.6f}")
    w("  (201) uses m = 2 and is correct as printed.")
    w("")

    s = acoustic_scale()
    w("Acoustic scale, from Annals II §8.3.2's own model")
    w(f"  n = 1, h = {H}, Omega_B = {OMEGA_B}, flat matter-dominated, z_* = {Z_STAR:.0f}")
    w(f"  R(eta_*)  = {s['R_star']:.4f}")
    w(f"  c_s       = {s['c_s']:.4f}")
    w(f"  eta_*     = {s['eta_star']:.5f} / H0")
    w(f"  dEta_*    = {s['d_eta']:.5f} / H0")
    w(f"  r_s       = {s['r_s']:.5f} / H0")
    w(f"  ell_A     = pi dEta_* / r_s = {s['ell_A']:.1f}")
    w("")
    w("Dropped acoustic modulation, 1 - cos(k r_s), with k ~ ell / dEta_*")
    for ell in (2, 5, 10, 15, 20, 25, 30, 40):
        err = 1 - np.cos(np.pi * ell / s["ell_A"])
        w(f"    ell = {ell:3d}    k r_s = {np.pi * ell / s['ell_A']:.4f}    {100 * err:6.2f}%")
    w("")
    w("Largest ell at each tolerance")
    adopted = None
    for tol in TOLERANCES:
        # Scan upward and stop at the FIRST violation. 1 - cos(k r_s) is periodic,
        # so it falls back inside tolerance near k r_s = 2 pi; a max() over a range
        # silently returns that spurious high branch instead of the plateau edge.
        ell_max = 2
        while 1 - np.cos(np.pi * (ell_max + 1) / s["ell_A"]) <= tol:
            ell_max += 1
        mark = ""
        if abs(tol - ADOPTED_TOLERANCE) < 1e-12:
            adopted, mark = ell_max, "   <- adopted"
        w(f"    {100 * tol:5.1f}%   ell <= {ell_max:3d}{mark}")
    w("")
    w(f"ADOPTED: 2 <= ell <= {adopted}, tolerance {100 * ADOPTED_TOLERANCE:.0f}%")
    w("  lower bound: the quadrupole. There is no monopole in the CGI approach")
    w("  (Annals II p. 366) and the dipole is frame-dependent. The late ISW")
    w("  vanishes in the flat matter-dominated model the comparison uses, so the")
    w("  low-ell end carries no secondary contamination.")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("\n".join(lines))
    print(f"\nwrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
