#!/usr/bin/env python3
"""The honest $\\ell$ range: where F3's $k$ integral has actually converged.

    python scripts/derive_ell_convergence.py

**Two independent limits bound what F3 may claim, and they are not the same
limit.** `derive_ell_range.py` gives the *physics* one: *Annals II*'s (186)
drops the acoustic modulation $1-\\cos(kr_s)$, which costs 4.75% at $\\ell=20$
and grows, so above $\\ell\\simeq20$ the spectrum is missing real physics however
well it is integrated. This script gives the *numerical* one: the $k$ grid stops
at $k_{\\max}=420$ where the diffusion damping is still 0.89, so the integral is
truncated rather than converged, and the published range cannot extend past
where that truncation matters either.

**The earlier measurement of this was taken on an aliased $\\eta$ grid** and is
withdrawn — finding T-3. Every run here derives `n_eta` from its own
$k_{\\max}$, so each cut-off is integrated at the resolution it needs rather
than at a resolution chosen once for the smallest.

The reported number is the fractional change in $D_\\ell$ between the shipped
$k_{\\max}$ and the largest computed, which is an estimate of what truncation
costs, not a bound on it. It is stated that way in the output.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from functions.background.flrw import CDM_MODEL, LCDM_MODEL  # noqa: E402
from functions.spectra.decoupling import Weighting  # noqa: E402
from functions.spectra.pipeline import required_n_eta, run  # noqa: E402

OUT = ROOT / "diagnostics"

#: What F3 ships with, and the cut-offs it is measured against.
SHIPPED_K_MAX = 420.0
CUTOFFS = (210.0, 420.0, 840.0, 1260.0)
DK = np.pi / 6.0

ELLS = np.array([2, 5, 10, 20, 30, 50, 100])

#: Tolerances the published range is quoted at.
BANDS = (0.01, 0.02, 0.05)


def spectrum(model, k_max: float) -> np.ndarray:
    k = np.arange(0.05, k_max, DK)
    out = run(model, ells=ELLS, k_com=k, weighting=Weighting.STANDARD_ISW, n_eta=None)
    return np.asarray(out.spectrum.d_ell()), out


def main() -> int:
    lines: list[str] = []

    def say(s: str = "") -> None:
        print(s)
        lines.append(s)

    say("Criterion 5 — where F3's k integral has converged")
    say("Generated by scripts/derive_ell_convergence.py. Do not edit by hand.")
    say()
    say("The eta grid is DERIVED from k_max in every run below, so each cut-off")
    say("is integrated at the resolution it needs. The earlier version of this")
    say("measurement was taken on a fixed, aliased grid and is withdrawn (T-3).")
    say()

    worst: dict[int, float] = {}
    for name, model in (("standard CDM", CDM_MODEL), ("LambdaCDM", LCDM_MODEL)):
        say(f"--- {name} " + "-" * max(0, 52 - len(name)))
        curves: dict[float, np.ndarray] = {}
        for k_max in CUTOFFS:
            d, run_out = spectrum(model, k_max)
            curves[k_max] = d
            say(f"  k_max={k_max:7.1f}  n_eta={run_out.n_eta:6d}  "
                f"({run_out.eta_points_per_period:4.1f} samples/oscillation)  "
                f"damping at edge {run_out.damping_at_k_max:.3f}")
        say()
        ref = curves[CUTOFFS[-1]]
        header = "    l  " + "".join(f"{c:>12.0f}" for c in CUTOFFS) + "   shipped err"
        say(header)
        for j, ell in enumerate(ELLS):
            row = f"  {ell:4d}  " + "".join(f"{curves[c][j]:12.5g}" for c in CUTOFFS)
            err = abs(curves[SHIPPED_K_MAX][j] - ref[j]) / abs(ref[j])
            worst[int(ell)] = max(worst.get(int(ell), 0.0), err)
            say(row + f"   {err:10.2%}")
        say()

    say("--- the numerical limit, worse of the two models " + "-" * 15)
    say("  Fractional change in D_l between the shipped k_max=420 and k_max=1260.")
    say("  An estimate of what truncation costs, not a bound on it.")
    say()
    for tol in BANDS:
        ok = [l for l in ELLS if worst[int(l)] <= tol]
        top = max(ok) if ok else None
        say(f"    {tol:5.0%}   l <= {top if top is not None else '—'}")
    say()
    say("--- the two limits together " + "-" * 36)
    say("  PHYSICS   (186) drops the acoustic modulation: 5% at l <= 20")
    say("            from scripts/derive_ell_range.py, unchanged")
    say(f"  NUMERICS  k-grid truncation at 5%: l <= "
        f"{max([l for l in ELLS if worst[int(l)] <= 0.05], default='—')}")
    say()
    binding = "physics" if max([l for l in ELLS if worst[int(l)] <= 0.05], default=0) >= 20 \
        else "numerics"
    say(f"  The {binding.upper()} limit binds. F3 is published over the range both")
    say("  allow, and the caption states which one sets it.")
    say()

    OUT.mkdir(exist_ok=True)
    path = OUT / "ell-convergence-v1.0.0.txt"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
