#!/usr/bin/env python3
"""D1 — the relative-sign control. A wiring check, not evidence.

    python scripts/diagnostic_d1_sign_control.py

Writes diagnostics/d1-sign-control-v1.0.0.txt and
diagnostics/d1-sign-control-v1.0.0.png.

**This lives in diagnostics/, not figures/.** A control is not evidence, so it is
not a released figure and does not appear in the supplement.

**What it controls.** The free-streaming bracket is run with its relative sign
flipped. That is not a different physical model: it is the same recursion written
in the other candidate harmonic normalisation, the $c^2=-1$ case. Under
$Q_{A_\\ell}\\to\\lambda^\\ell Q_{A_\\ell}$, $\\tau_\\ell\\to\\lambda^{-\\ell}\\tau_\\ell$
the raising and lowering terms acquire $\\lambda^{-1}$ and $\\lambda^{+1}$, so
their relative coefficient carries $\\lambda^{-2}$ and the relative sign flips
whenever $c^2=-1$. The two candidate normalisations differ by exactly
$\\lambda=i$.

**Why it is the cheapest check in the bundle.** With both couplings carrying the
same sign the hierarchy grows instead of projecting an oscillatory solution onto
higher multipoles. It does not merely disagree with the external form, it
diverges — a failure of known shape, which is the most legible kind. It is
acceptance criterion 4, and it replaces the $\\pm(\\ell+2)$ control, which would
have exercised a second-order term this release does not contain.

**It is also criterion 3 in executable form.** The correct normalisation
reproduces the real, opposite-sign hierarchy of Hu & Sugiyama, Ma & Bertschinger
and Seljak & Zaldarriaga; the other does not. Both run end to end; only one
matches.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from functions.harmonics.free_streaming import (  # noqa: E402
    analytic_projection,
    free_stream,
)
from functions.plotting.style import (  # noqa: E402
    DETERMINISTIC_METADATA,
    INK,
    SERIES,
    use_house_style,
)

K_COM = 1.0
ELL_MAX = 80
ELL_REPORTED = (2, 5, 10, 20)
OUT = ROOT / "diagnostics"
TOLERANCE = 1e-8
DIVERGENCE_FACTOR = 1e3


def main() -> int:
    eta = np.linspace(0.0, 20.0, 1200)
    window = (eta > 2.0) & (eta < 18.0)
    good = free_stream(K_COM, eta, ell_max=ELL_MAX, normalisation="alpha")
    bad = free_stream(K_COM, eta, ell_max=ELL_MAX, normalisation="alpha", sign_control=True)

    lines = [
        "D1 — relative-sign control",
        "Generated by scripts/diagnostic_d1_sign_control.py. Do not edit by hand.",
        "",
        "The free-streaming bracket run with its relative sign flipped: the",
        "c^2 = -1 case of the harmonic phase question, not a different model.",
        "Acceptance criterion 4, and criterion 3 in executable form.",
        "",
        f"  k_com = {K_COM}   ell_max = {ELL_MAX}   window {eta[window][0]:.1f} < eta < {eta[window][-1]:.1f}",
        "",
        "  ell   |X_l - j_l| correct      max|X_l| correct   max|X_l| control    ratio",
    ]
    ok = True
    rows = []
    for ell in ELL_REPORTED:
        j = analytic_projection(K_COM, eta, 0.0, ell)
        err = float(np.max(np.abs(good.values[window, ell] - j[window])))
        amp_good = float(np.max(np.abs(good.values[window, ell])))
        amp_bad = float(np.max(np.abs(bad.values[window, ell])))
        ratio = amp_bad / amp_good
        rows.append((ell, err, amp_good, amp_bad, ratio))
        lines.append(f"  {ell:3d}   {err:.3e}              {amp_good:.4e}         "
                     f"{amp_bad:.4e}      {ratio:11.1f}")
        if err > TOLERANCE or ratio < DIVERGENCE_FACTOR:
            ok = False

    lines += [
        "",
        f"  correct recursion on j_l to better than {TOLERANCE:.0e}: "
        f"{'yes' if all(r[1] <= TOLERANCE for r in rows) else 'NO'}",
        f"  control diverges by more than {DIVERGENCE_FACTOR:.0e}: "
        f"{'yes' if all(r[4] >= DIVERGENCE_FACTOR for r in rows) else 'NO'}",
        "",
        f"  {'PASS' if ok else 'FAIL'}",
    ]
    report = "\n".join(lines) + "\n"
    OUT.mkdir(exist_ok=True)
    (OUT / "d1-sign-control-v1.0.0.txt").write_text(report, encoding="utf-8", newline="\n")
    print(report)

    # --- the picture. Control in slot 4, the control slot, directly labelled ---
    use_house_style()
    fig, ax = plt.subplots(figsize=(5.4, 3.3))
    fig.subplots_adjust(top=0.84, bottom=0.17, left=0.13, right=0.97)
    ell = 5
    j = analytic_projection(K_COM, eta, 0.0, ell)
    ax.semilogy(eta[window], np.abs(good.values[window, ell]) + 1e-20,
                color=SERIES[1], lw=1.7, label=f"correct recursion, $\\ell={ell}$")
    ax.semilogy(eta[window], np.abs(j[window]) + 1e-20,
                color=INK["muted"], lw=1.1, ls=(0, (2.2, 2.2)), label=r"$j_\ell$")
    ax.semilogy(eta[window], np.abs(bad.values[window, ell]) + 1e-20,
                color=SERIES[4], lw=1.7, label="control: relative sign flipped")
    ax.set_xlabel(r"conformal time  $\eta$   [$1/k_{\rm com}$]")
    ax.set_ylabel(r"$|\alpha_\ell^{-1}\tau_\ell|$")
    ax.set_title("D1   relative-sign control — diagnostic, not evidence",
                 color=INK["primary"], pad=8)
    ax.legend(loc="upper left", bbox_to_anchor=(0.0, -0.22), ncol=1, fontsize=7.2)
    fig.subplots_adjust(bottom=0.40)
    path = OUT / "d1-sign-control-v1.0.0.png"
    # Deterministic metadata, as every released figure gets. See T-2 and
    # functions/plotting/style.py: this one writes its own file rather than
    # going through save_figure, so it has to say so itself.
    fig.savefig(path, metadata=DETERMINISTIC_METADATA["png"])
    plt.close(fig)
    print(f"wrote {path.relative_to(ROOT)}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
