#!/usr/bin/env python3
r"""D2 — the round-trip residual, as a number and as an identity.

    python scripts/diagnostic_d2_roundtrip.py

**Acceptance criterion 2.** The figure plan asks for *"a number with its
tolerance. If it is machine precision it is not a chart"*, and it is not a
chart. The residual is not merely small: it is **identically zero in exact
symbolic arithmetic**, so this diagnostic reports the identity first and the
floating-point evaluation second.

Decision S14 supplies the target and the reason it is a check rather than a
rederivation: $\mathcal B_1=\mathrm D_a\ln T+A_a$ does not change form off the
Newtonian frame, so a generic-$u^a$ construction boosted to
$\tilde u^a=u^a+v^a$ must return $\tilde{\mathcal B}_1=\mathcal B_1+\dot v_a$ —
**no shear, no $Hv$** — and anything else is a bug here.

What makes the result worth reporting is not that it vanishes but **why**. The
$Hv$ enters twice from the same $H$: with a minus sign through
$v_a\dot{\overline{\ln T}}$ in the moving projector, and with a plus sign
through $\tfrac13\Theta$ in $v^b\nabla_bu_a$. The shear and vorticity
contractions are written in full and leave at $O(\varepsilon^2)$. Both halves
are printed below so the cancellation can be read rather than trusted.
"""

from __future__ import annotations

import random
import sys
from pathlib import Path

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from functions.frames import (  # noqa: E402
    EPS,
    FrameChange,
    boosted_acceleration,
    boosted_temperature_gradient,
    roundtrip_residual,
)

OUT = ROOT / "diagnostics"

#: Draws used for the floating-point evaluation. The identity does not need
#: them; a reader who wants a number rather than an identity does.
DRAWS = 64
TOLERANCE = 1e-15


def _vec(name: str) -> sp.Matrix:
    return sp.Matrix(3, 1, lambda i, _j: EPS * sp.Symbol(f"{name}_{i+1}", real=True))


def main() -> int:
    lines: list[str] = []

    def say(s: str = "") -> None:
        print(s)
        lines.append(s)

    say("D2 — round-trip residual, covariant -> mode -> covariant")
    say("Generated by scripts/diagnostic_d2_roundtrip.py. Do not edit by hand.")
    say()
    say("Acceptance criterion 2, target from decision S14:")
    say("    B1~ = B1 + vdot_a,   no shear, no Hv")
    say()

    fc = FrameChange.generic()
    grad, accel = _vec("DlnT"), _vec("A")

    say("--- the cancellation, read off each half " + "-" * 23)
    g_extra = sp.expand(boosted_temperature_gradient(grad, fc)[0] - grad[0])
    a_extra = sp.expand(boosted_acceleration(accel, fc)[0] - accel[0] - fc.v_dot[0])
    say(f"  temperature gradient picks up : {g_extra}")
    say(f"  acceleration picks up         : {a_extra}   (beyond vdot)")
    say(f"  sum                           : {sp.simplify(g_extra + a_extra)}")
    say()
    say("  It is the SAME H twice: minus through v_a d(lnT)/dt in the moving")
    say("  projector, plus through Theta/3 in v^b grad_b u_a. The cancellation")
    say("  is structural, not a coincidence of two fitted coefficients.")
    say()

    say("--- shear and vorticity " + "-" * 40)
    leftover = {str(s) for s in boosted_acceleration(accel, fc).free_symbols}
    shear = sorted(s for s in leftover if s.startswith("sigma"))
    vort = sorted(s for s in leftover if s.startswith("omega"))
    say(f"  sigma_ab v^b and eps_abc v^b omega^c are formed in full, then")
    say(f"  removed at O(eps^2) by series expansion, not by hand.")
    say(f"  shear symbols surviving at first order    : {shear or 'none'}")
    say(f"  vorticity symbols surviving at first order: {vort or 'none'}")
    say()

    residual = roundtrip_residual()
    exact = all(c == 0 for c in residual)
    say("--- the residual " + "-" * 47)
    say(f"  symbolic : B1~ - (B1 + vdot) = {list(residual)}")
    say(f"  identically zero in exact arithmetic: {'YES' if exact else 'NO'}")
    say()

    rng = random.Random(20261009)
    worst = 0.0
    for _ in range(DRAWS):
        subs = {s: rng.uniform(-1.0, 1.0) for s in residual.free_symbols}
        worst = max(worst, max(abs(float(sp.N(c.subs(subs)))) for c in residual))
    say(f"  floating point, {DRAWS} random draws, worst |residual| = {worst:.3e}")
    say(f"  tolerance {TOLERANCE:.0e}")
    say()
    say("  The floating-point line is the weaker statement and is kept because")
    say("  it is the one a reader can check in ten seconds. The identity above")
    say("  is what the criterion actually rests on.")
    say()

    ok = exact and worst < TOLERANCE
    say("  PASS" if ok else "  FAIL")

    OUT.mkdir(exist_ok=True)
    path = OUT / "d2-roundtrip-v1.0.0.txt"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"\nwrote {path.relative_to(ROOT)}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
