#!/usr/bin/env python3
"""Generate the supplement's figure section from captions/ and figures/.

    python scripts/make_figure_pages.py

Writes `supplementary-materials/figures-v1.0.0.tex`, which the supplement
includes. One float per figure that actually exists, carrying the figure and its
caption.

**A caption file is the single source.** Each `captions/*.md` opens with a TOML
front-matter block delimited by `+++`, holding the LaTeX caption and the paths;
the markdown below it is the standalone long-form caption a reader opens on its
own. The supplement takes the front matter, so the two cannot drift.

**A figure appears here only once it has been generated.** Nothing is promised in
the supplement that is not in the tree, and the section states what is still
outstanding rather than quietly omitting it.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAPTIONS = ROOT / "captions"
OUT = ROOT / "supplementary-materials" / "figures-v1.0.0.tex"

#: The agreed set, in order. See captions/FIGURE-PLAN-v1.0.0.md.
PLANNED = [
    ("F1", "the Appendix F match"),
    ("F2", "truncation convergence, both frames"),
    ("F3", "angular autocorrelation"),
    ("F4", "real-space angular correlation"),
    ("F5", "source decomposition, two frames"),
    ("F6", "impact of the approximations"),
    ("F7", "frame specialisation"),
    ("F8", "coupling schematic"),
]


def front_matter(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("+++"):
        return None
    _, block, _ = text.split("+++", 2)
    return tomllib.loads(block)


def main() -> int:
    entries = []
    for path in sorted(CAPTIONS.glob("*.md")):
        fm = front_matter(path)
        if not fm:
            continue
        artefact = ROOT / fm["artefact"]
        if not artefact.exists():
            print(f"  skipping {fm['id']}: {fm['artefact']} not generated yet")
            continue
        entries.append((fm, path))
    entries.sort(key=lambda e: e[0].get("order", 99))

    lines = [
        "% GENERATED by scripts/make_figure_pages.py from captions/ and figures/.",
        "% Do not edit by hand.",
        "",
    ]
    for fm, path in entries:
        rel = str(Path(fm["artefact"]).as_posix())
        lines += [
            "\\begin{figure}[p]",
            "\\centering",
            f"\\includegraphics[width=\\textwidth]{{{rel}}}",
            "\\caption[%s]{\\textbf{%s --- %s.} %s\\\\[2pt]\\footnotesize\\emph{Evidence "
            "category:} %s. \\emph{Generated by} \\texttt{%s}. \\emph{Standalone caption:} "
            "\\texttt{%s}.}"
            % (
                fm["title"],
                fm["id"],
                fm["title"],
                fm["caption"].strip().replace("\n", " "),
                fm.get("category", "—"),
                fm["script"].replace("_", "\\_"),
                path.relative_to(ROOT).as_posix().replace("_", "\\_"),
            ),
            f"\\label{{fig:{fm['id'].lower()}}}",
            "\\end{figure}",
            "",
        ]

    done = {fm["id"] for fm, _ in entries}
    outstanding = [f"\\textbf{{{i}}} {d}" for i, d in PLANNED if i not in done]
    if outstanding:
        lines += [
            "\\noindent\\textit{Outstanding at this release candidate:} "
            + "; ".join(outstanding)
            + ". The agreed specification for the full set is "
            "\\texttt{captions/FIGURE-PLAN-v1.0.0.md}.",
            "",
        ]

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}  —  {len(entries)} of {len(PLANNED)} figures included")
    return 0


if __name__ == "__main__":
    sys.exit(main())
