#!/usr/bin/env python3
"""Generate the audit tables from config/implementation-register.toml.

    python scripts/make_tables.py

Writes, into tables/:

    equations-v1.0.0.{csv,tex}    published equation -> provenance -> code -> test
    parameters-v1.0.0.{csv,tex}   every number the numerics use, and where it came from
    notation-v1.0.0.{csv,tex}     symbols, and their names in the code
    conventions-v1.0.0.{csv,tex}  the convention-translation table

The LaTeX tables are included by SUPPLEMENTARY-MATERIAL-v1.0.0.tex. **They are
generated, never hand-written**, so the supplement cannot drift from the code;
and `tests/test_register.py` resolves every module and object named in the
register, so a rename breaks the build rather than quietly falsifying a table.

Equation numbers in the register are PUBLISHED numbers.
"""

from __future__ import annotations

import csv
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTER = ROOT / "config" / "implementation-register.toml"
TABLES = ROOT / "tables"
VERSION = "1.0.0"


def load() -> dict:
    with REGISTER.open("rb") as fh:
        return tomllib.load(fh)


def code_file(row: dict) -> str:
    """The .py file implementing this entry, or the pending marker."""
    if not row.get("module"):
        return "—"
    return row["module"].replace(".", "/") + ".py"


def code_object(row: dict) -> str:
    return row.get("object") or "—"


def tt(s: str) -> str:
    """\\texttt, with underscores escaped and breakable so long names wrap."""
    if s in ("—", "-", ""):
        return "—"
    # Underscores were already breakable; `/` and `::` were not, so a long
    # path or a `module::test` name stayed one unbreakable box and pushed the
    # table off the page however wide the column was. That was 156pt of a
    # released supplement running past the margin.
    out = s.replace("_", "\\_\\allowbreak{}")
    out = out.replace("/", "/\\allowbreak{}").replace("::", "::\\allowbreak{}")
    return "\\texttt{" + out + "}"


def write_csv(name: str, header: list[str], rows: list[list[str]]) -> Path:
    path = TABLES / f"{name}-v{VERSION}.csv"
    with path.open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        w.writerows(rows)
    return path


def write_tex(name: str, caption: str, colspec: str, header: list[str],
              rows: list[list[str]], label: str, landscape: bool = False) -> Path:
    path = TABLES / f"{name}-v{VERSION}.tex"
    out = [
        "% GENERATED by scripts/make_tables.py from config/implementation-register.toml.",
        "% Do not edit by hand.",
        "\\begin{landscape}" if landscape else "",
        "\\begingroup",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\renewcommand{\\arraystretch}{1.25}",
        f"\\begin{{longtable}}{{{colspec}}}",
        f"\\caption{{{caption}}}\\label{{{label}}}\\\\",
        "\\toprule",
        " & ".join(f"\\textbf{{{h}}}" for h in header) + " \\\\",
        "\\midrule",
        "\\endfirsthead",
        "\\toprule",
        " & ".join(f"\\textbf{{{h}}}" for h in header) + " \\\\",
        "\\midrule",
        "\\endhead",
        "\\bottomrule",
        "\\endfoot",
    ]
    for r in rows:
        out.append(" & ".join(r) + " \\\\")
    out += ["\\end{longtable}", "\\endgroup"]
    if landscape:
        out.append("\\end{landscape}")
    out.append("")
    path.write_text("\n".join(out), encoding="utf-8", newline="\n")
    return path


def main() -> int:
    reg = load()
    TABLES.mkdir(exist_ok=True)
    sources = reg["sources"]
    written: list[Path] = []

    # --- equations ----------------------------------------------------------
    header = ["Quantity", "Source", "Equation", "File", "Object", "Checked by"]
    csv_rows, tex_rows = [], []
    for e in reg["equations"]:
        f, obj = code_file(e), code_object(e)
        test = e.get("test") or "—"
        csv_rows.append([e["key"], e["quantity"], sources[e["source"]]["text"],
                         e["equation"], f, obj, test, e.get("note", "")])
        tex_rows.append([e["quantity"], sources[e["source"]]["short"], e["equation"],
                         tt(f), tt(obj), tt(test)])
    written.append(write_csv("equations",
                             ["key", "quantity", "source", "equation", "file", "object",
                              "test", "note"],
                             csv_rows))
    written.append(write_tex(
        "equations",
        "Equations implemented in the numerics, with their provenance and the code "
        "that implements them. Equation numbers are those of the \\emph{published} "
        "papers. Rows with no code are not yet implemented.",
        "@{}p{50mm}p{16mm}p{22mm}p{48mm}p{22mm}p{40mm}@{}",
        header, tex_rows, "tab:equations", landscape=True))

    # --- parameters ---------------------------------------------------------
    header = ["Symbol", "Code", "Value", "Provenance", "Set in"]
    csv_rows, tex_rows = [], []
    for p in reg["parameters"]:
        csv_rows.append([p["symbol"], p["code"], p["value"], p["units"],
                         p["source"], p["where"], p.get("note", "")])
        tex_rows.append([
            p["symbol"],
            tt(p["code"]),
            p["value"],
            p["source"],
            tt(p["where"]),
        ])
    written.append(write_csv("parameters",
                             ["symbol", "code", "value", "units", "source", "where", "note"],
                             csv_rows))
    written.append(write_tex(
        "parameters",
        "Every number the numerics use. \\emph{Provenance} distinguishes values "
        "taken from the source paper, standard values that are not, values "
        "derived here, and values stipulated for this release.",
        "@{}p{0.10\\textwidth}p{0.22\\textwidth}p{0.12\\textwidth}p{0.26\\textwidth}p{0.26\\textwidth}@{}",
        header, tex_rows, "tab:parameters"))

    # --- notation -----------------------------------------------------------
    header = ["Symbol", "In code", "Meaning", "Note"]
    csv_rows, tex_rows = [], []
    for n in reg["notation"]:
        csv_rows.append([n["symbol"], n["code"], n["meaning"], n.get("note", "")])
        tex_rows.append([n["symbol"], tt(n["code"].replace("---", "—")),
                         n["meaning"], n.get("note", "") or "—"])
    written.append(write_csv("notation", ["symbol", "code", "meaning", "note"], csv_rows))
    written.append(write_tex(
        "notation",
        "Notation, and the names the quantities carry in the code. The "
        "mode/multipole distinction is the one that matters most: "
        "\\emph{Annals II} notes that it is not made in Bardeen-variable treatments.",
        "@{}p{0.12\\textwidth}p{0.24\\textwidth}p{0.30\\textwidth}p{0.30\\textwidth}@{}",
        header, tex_rows, "tab:notation"))

    # --- translations (Table V) ---------------------------------------------
    # Rows are couplings, columns are conventions, as the float specification
    # asks. **Every cell names the sheet line it comes from** and no cell is
    # blank: where a treatment has no established counterpart the cell says so,
    # which is the honest content rather than a gap. The sheet's own closing
    # section records BF and Pitrou as unsettled at the level of hierarchy
    # coefficients, which is why those columns are mostly "not established".
    COLS = [("mge99", "MGE99"), ("cl", "CL"), ("th_k", "Th, K/$\\Pi$"),
            ("th_t", "Th, $\\dot{\\mathcal T}$"), ("bf", "BF"), ("p09", "P09")]
    header = ["Coupling", "Sheet"] + [h for _k, h in COLS]
    csv_rows, tex_rows = [], []
    for t in reg["translations"]:
        csv_rows.append([t["key"], t["coupling"], t["expression"], t["sheet"],
                         str(t["kinematic"])] + [t[k] for k, _h in COLS])
        tex_rows.append([t["coupling"], tt(t["sheet"])] + [t[k] for k, _h in COLS])
    written.append(write_csv(
        "translations",
        ["key", "coupling", "expression", "sheet", "kinematic"] + [k for k, _h in COLS],
        csv_rows))
    written.append(write_tex(
        "translations",
        "The couplings of this reconstruction written in each external convention. "
        "Every cell is derived from the line of \\texttt{provenance/conventions.md} "
        "named in the \\emph{Sheet} column; no cell is blank, and a treatment with no "
        "established counterpart says so rather than being left to inference. "
        "\\textbf{The thesis takes two columns and they differ on exactly the "
        "kinematic rows} --- the $\\dot{\\mathcal T}$ form moves every kinematic term "
        "to the right-hand side, flipping its overall sign against the K/$\\Pi$ form. "
        "On the remaining rows the two agree, and the table says \\emph{as Th-K} "
        "rather than restating them: a difference in wording where there is none in "
        "substance is how two conventions get conflated while appearing distinct.",
        "@{}p{24mm}p{13mm}p{34mm}p{30mm}p{21mm}p{30mm}p{28mm}p{28mm}@{}",
        header, tex_rows, "tab:translations", landscape=True))

    # --- conventions --------------------------------------------------------
    header = ["Treatment", "Variable", "Bracket weights", "Phase convention",
              "Transformation applied here", "How it was checked"]
    csv_rows, tex_rows = [], []
    for c in reg["conventions"]:
        short = reg["sources"][c["source"]]["short"]
        csv_rows.append([short, c["where"], c["variable"], c["weights"],
                         c["phase"], c["applied"], c["checked"], c["test"]])
        tex_rows.append([f"{short}\\\\ \\footnotesize {c['where']}", c["variable"],
                         c["weights"], c["phase"], c["applied"], c["checked"]])
    written.append(write_csv(
        "conventions",
        ["treatment", "where", "variable", "weights", "phase", "applied", "checked", "test"],
        csv_rows))
    written.append(write_tex(
        "conventions",
        "How each treatment in the foundational literature writes the same "
        "hierarchy, and how this bundle checked it. The two conventions in the "
        "literature are related by $\\tau_\\ell\\to c^\\ell\\tau_\\ell$ with "
        "$c^2=-1$ and nothing else. \\textbf{Where the transformation applied is "
        "``none'' that is a choice, not a derivation} --- which is why "
        "acceptance criterion~3 was reopened; see \\S\\ref{sec:conventions}.",
        "@{}p{24mm}p{26mm}p{20mm}p{34mm}p{40mm}p{48mm}@{}",
        header, tex_rows, "tab:conventions", landscape=True))

    for p in written:
        print(f"wrote {p.relative_to(ROOT)}")
    n_pending = sum(1 for e in reg["equations"] if not e.get("module"))
    print(f"  {len(reg['equations'])} equations ({n_pending} pending), "
          f"{len(reg['parameters'])} parameters, {len(reg['notation'])} notation entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
