#!/usr/bin/env python3
"""Generate the audit tables from config/implementation-register.toml.

    python scripts/make_tables.py

Writes, into tables/:

    equations-v1.0.0.{csv,tex}    published equation -> provenance -> code -> test
    parameters-v1.0.0.{csv,tex}   every number the numerics use, and where it came from
    notation-v1.0.0.{csv,tex}     symbols, and their names in the code
    conventions-v1.0.0.{csv,tex}  the convention-translation table

The LaTeX tables are included by SUPPLEMENTARY-MATERIAL-v1.0.0.tex. **They are
generated, never hand-written**, so the supplement cannot drift from the code;
and `tests/test_register.py` resolves every module and object named in the
register, so a rename breaks the build rather than quietly falsifying a table.

Equation numbers in the register are PUBLISHED numbers.
"""

from __future__ import annotations

import csv
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTER = ROOT / "config" / "implementation-register.toml"
TABLES = ROOT / "tables"
VERSION = "1.0.0"


def load() -> dict:
    with REGISTER.open("rb") as fh:
        return tomllib.load(fh)


def code_file(row: dict) -> str:
    """The .py file implementing this entry, or the pending marker."""
    if not row.get("module"):
        return "—"
    return row["module"].replace(".", "/") + ".py"


def code_object(row: dict) -> str:
    return row.get("object") or "—"


def tt(s: str) -> str:
    """\\texttt, with underscores escaped and breakable so long names wrap."""
    if s in ("—", "-", ""):
        return "—"
    return "\\texttt{" + s.replace("_", "\\_\\allowbreak{}") + "}"


def write_csv(name: str, header: list[str], rows: list[list[str]]) -> Path:
    path = TABLES / f"{name}-v{VERSION}.csv"
    with path.open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        w.writerows(rows)
    return path


def write_tex(name: str, caption: str, colspec: str, header: list[str],
              rows: list[list[str]], label: str, landscape: bool = False) -> Path:
    path = TABLES / f"{name}-v{VERSION}.tex"
    out = [
        "% GENERATED by scripts/make_tables.py from config/implementation-register.toml.",
        "% Do not edit by hand.",
        "\\begin{landscape}" if landscape else "",
        "\\begingroup",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\renewcommand{\\arraystretch}{1.25}",
        f"\\begin{{longtable}}{{{colspec}}}",
        f"\\caption{{{caption}}}\\label{{{label}}}\\\\",
        "\\toprule",
        " & ".join(f"\\textbf{{{h}}}" for h in header) + " \\\\",
        "\\midrule",
        "\\endfirsthead",
        "\\toprule",
        " & ".join(f"\\textbf{{{h}}}" for h in header) + " \\\\",
        "\\midrule",
        "\\endhead",
        "\\bottomrule",
        "\\endfoot",
    ]
    for r in rows:
        out.append(" & ".join(r) + " \\\\")
    out += ["\\end{longtable}", "\\endgroup"]
    if landscape:
        out.append("\\end{landscape}")
    out.append("")
    path.write_text("\n".join(out), encoding="utf-8", newline="\n")
    return path


def main() -> int:
    reg = load()
    TABLES.mkdir(exist_ok=True)
    sources = reg["sources"]
    written: list[Path] = []

    # --- equations ----------------------------------------------------------
    header = ["Quantity", "Source", "Equation", "File", "Object", "Checked by"]
    csv_rows, tex_rows = [], []
    for e in reg["equations"]:
        f, obj = code_file(e), code_object(e)
        test = e.get("test") or "—"
        csv_rows.append([e["key"], e["quantity"], sources[e["source"]]["text"],
                         e["equation"], f, obj, test, e.get("note", "")])
        tex_rows.append([e["quantity"], sources[e["source"]]["short"], e["equation"],
                         tt(f), tt(obj), tt(test)])
    written.append(write_csv("equations",
                             ["key", "quantity", "source", "equation", "file", "object",
                              "test", "note"],
                             csv_rows))
    written.append(write_tex(
        "equations",
        "Equations implemented in the numerics, with their provenance and the code "
        "that implements them. Equation numbers are those of the \\emph{published} "
        "papers. Rows with no code are not yet implemented.",
        "@{}p{56mm}llp{54mm}p{24mm}p{44mm}@{}",
        header, tex_rows, "tab:equations", landscape=True))

    # --- parameters ---------------------------------------------------------
    header = ["Symbol", "Code", "Value", "Provenance", "Set in"]
    csv_rows, tex_rows = [], []
    for p in reg["parameters"]:
        csv_rows.append([p["symbol"], p["code"], p["value"], p["units"],
                         p["source"], p["where"], p.get("note", "")])
        tex_rows.append([
            p["symbol"],
            tt(p["code"]),
            p["value"],
            p["source"],
            tt(p["where"]),
        ])
    written.append(write_csv("parameters",
                             ["symbol", "code", "value", "units", "source", "where", "note"],
                             csv_rows))
    written.append(write_tex(
        "parameters",
        "Every number the numerics use. \\emph{Provenance} distinguishes values "
        "taken from the source paper, standard values that are not, values "
        "derived here, and values stipulated for this release.",
        "@{}llllp{0.30\\textwidth}@{}",
        header, tex_rows, "tab:parameters"))

    # --- notation -----------------------------------------------------------
    header = ["Symbol", "In code", "Meaning", "Note"]
    csv_rows, tex_rows = [], []
    for n in reg["notation"]:
        csv_rows.append([n["symbol"], n["code"], n["meaning"], n.get("note", "")])
        tex_rows.append([n["symbol"], tt(n["code"].replace("---", "—")),
                         n["meaning"], n.get("note", "") or "—"])
    written.append(write_csv("notation", ["symbol", "code", "meaning", "note"], csv_rows))
    written.append(write_tex(
        "notation",
        "Notation, and the names the quantities carry in the code. The "
        "mode/multipole distinction is the one that matters most: "
        "\\emph{Annals II} notes that it is not made in Bardeen-variable treatments.",
        "@{}llp{0.33\\textwidth}p{0.33\\textwidth}@{}",
        header, tex_rows, "tab:notation"))

    # --- conventions --------------------------------------------------------
    header = ["Treatment", "Variable", "Bracket weights", "Phase convention",
              "Transformation applied here", "How it was checked"]
    csv_rows, tex_rows = [], []
    for c in reg["conventions"]:
        short = reg["sources"][c["source"]]["short"]
        csv_rows.append([short, c["where"], c["variable"], c["weights"],
                         c["phase"], c["applied"], c["checked"], c["test"]])
        tex_rows.append([f"{short}\\\\ \\footnotesize {c['where']}", c["variable"],
                         c["weights"], c["phase"], c["applied"], c["checked"]])
    written.append(write_csv(
        "conventions",
        ["treatment", "where", "variable", "weights", "phase", "applied", "checked", "test"],
        csv_rows))
    written.append(write_tex(
        "conventions",
        "How each treatment in the foundational literature writes the same "
        "hierarchy, and how this bundle checked it. The two conventions in the "
        "literature are related by $\\tau_\\ell\\to c^\\ell\\tau_\\ell$ with "
        "$c^2=-1$ and nothing else. \\textbf{Where the transformation applied is "
        "``none'' that is a choice, not a derivation} --- which is why "
        "acceptance criterion~3 was reopened; see \\S\\ref{sec:conventions}.",
        "@{}p{0.11\\textwidth}llp{0.17\\textwidth}p{0.20\\textwidth}p{0.24\\textwidth}@{}",
        header, tex_rows, "tab:conventions", landscape=True))

    for p in written:
        print(f"wrote {p.relative_to(ROOT)}")
    n_pending = sum(1 for e in reg["equations"] if not e.get("module"))
    print(f"  {len(reg['equations'])} equations ({n_pending} pending), "
          f"{len(reg['parameters'])} parameters, {len(reg['notation'])} notation entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
